name: qe-mini-example
channels:
  - default
dependencies:
  - python=3.7
  - sphinx=2.4.4
  - sympy
  - pip
  - pandas=1.0.4
  - matplotlib=3.2.1
  - pip:
    - jupyter-book
    - mlfinlab==0.12.3
    - sympy
    - mplfinance
    - yfinance
